// calling in express to use its methods and functionality
const express = require('express');

// call in our functions from the controller
const { getPayments, getPaymentByUsername, createPayment, updatePayment, deletePayment } = require('../controllers/paymentController.js');
//const { getPaymentByUsername } = require('../../frontend/src/services/apiService.js');

// set up our router instance
const router = express.Router();

// define our routes/endpoints
// to get all payments, we don't need to pass through the specific id of that payment
router.get('/', getPayments);
// to get a specific payment, we pass through that payments username
router.get('/:username', getPaymentByUsername);
// when creating a payment, we don't need to pass through a specific ID either, as it is autogenerated
router.post('/', createPayment);
// when updating a payment, we want to update a SPECIFIC one, so we specify the ID
router.put('/:id', updatePayment);
// when deleting we also pass an ID
router.delete('/:id', deletePayment);

// finally we export our routes
module.exports = router;