// calling in express to use its methods and functionality
const express = require('express');

const { verifyToken } = require('../middlewares/authMiddleware.js');

// call in our functions from the controller
const { getPayments, getPaymentByUsername, createPayment, updatePayment, deletePayment, getPendingPayments, getUpdatedStatusPayments, updatePaymentStatus } = require('../controllers/paymentController.js');
//const { getPaymentByUsername } = require('../../frontend/src/services/apiService.js');

// set up our router instance
const router = express.Router();

// define our routes/endpoints
// to get all payments, we don't need to pass through the specific id of that payment
router.get('/', getPayments);

//this gets all the payments according to the status being pending and returns them
router.get('/pending', getPendingPayments);

// this updates the status according to if you seleted the accepted or rejected button
router.get('/updatedStatus', getUpdatedStatusPayments);

// to get a specific payment, we pass through the username associated to them
router.get('/:username', verifyToken, getPaymentByUsername);
// when creating a payment, we don't need to pass through a specific ID either, as it is autogenerated
router.post('/', verifyToken, createPayment);
// when updating a payment, we want to update a SPECIFIC one, so we specify the ID
router.put('/:id', verifyToken, updatePayment);
// when deleting we also pass an ID
router.delete('/:id', verifyToken, deletePayment);
// Updating the status of the payment
router.put('/updateStatus/:id/:status', updatePaymentStatus)

// finally we export our routes
module.exports = router;